
modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/Leviathan-Studio/CraftStudioAPI" #optional
[[mods]] #mandatory
modId="craftstudioapi" #mandatory
version="${file.jarVersion}" #mandatory
displayName="CraftStudio API" #mandatory
updateJSONURL="https://leviathan-studio.com/craftstudioapi/update.json" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
credits="See https://github.com/Leviathan-Studio/CraftStudioAPI/blob/master/CREDITS.md" #optional
authors="ZeAmateis, Timmypote, Elisee, IncubeSupreme, Phenix246" #optional
description='''A CraftStudio API for models/animations support in Minecraft'''

[[dependencies.craftstudioapi]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.craftstudioapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
